//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAnswer
    {
        public int ID { get; set; }
        public string Text { get; set; }
        public bool IsCorrect { get; set; }
        public int IDqs { get; set; }
    
        public virtual GQuestion GQuestion { get; set; }
    }
}
