//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTestResult
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Group { get; set; }
        public System.DateTime Date { get; set; }
        public int Result { get; set; }
        public int IDts { get; set; }
    
        public virtual GTest GTest { get; set; }
    }
}
